# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EasyOrder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EasyOrder
  pod 'BraintreeDropIn'
  pod 'HCSStarRatingView', '~> 1.5'

end
